ContainerUI/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include(urls, namespace='main'), name='main'),
]

main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^upload/$', views.Upload, name='upload'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^api/crawl/', views.crawl, name='crawl'),
]

main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
import json


# Create your models here.


class Document(models.Model):
    docfile = models.FileField(upload_to='documents/%Y/%m/%d')


class ScrapyItem(models.Model):
    unique_id = models.CharField(max_length=100, null=True)
    data = models.TextField()  # this stands for our crawled data
    date = models.DateTimeField(default=timezone.now)

    # This is for basic and custom serialisation to return it to client as a JSON.
    @property
    def to_dict(self):
        data = {
            'data': json.loads(self.data),
            'date': self.date
        }
        return data

    def __str__(self):
        return self.unique_id

main/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms


invalid_error = 'User with this {} already exists.'


class LoginForm(auth_forms.AuthenticationForm):

    username = forms.CharField(max_length=254,
                               widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'required': 'True',
                                                             'placeholder': 'Username...'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                 'required': 'True',
                                                                 'placeholder': 'Password...'}))
    next_ = forms.CharField(widget=forms.HiddenInput())


class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file'
    )

main/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib import auth
import os
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login
from django.template import Context
from django.conf import settings
from django.http import HttpResponseRedirect

from .forms import DocumentForm
from .models import Document
from .forms import LoginForm

from uuid import uuid4
from urlparse import urlparse
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from django.views.decorators.http import require_POST, require_http_methods
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from scrapyd_api import ScrapydAPI
from main.models import ScrapyItem
from scrapy_app.scraper.spiders import scrapingdata

import ContainerUI
import scrapy_app


def login(request):
    redirect_to = request.POST.get('next_',
                                   request.GET.get('next', 'main:upload'))
    if request.user.is_authenticated():
        return redirect(redirect_to)
    if request.method == "POST":

        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            # Okay, security check complete. Log the user in.
            auth.login(request, form.get_user())
            return redirect(redirect_to)
    else:
        form = LoginForm(request, initial={'next_': redirect_to})

    return render(request, 'auth/login.html', {'form': form})


def logout(request):
    auth.logout(request)
    return redirect('main:login')


def Upload(request):
    if not request.user.is_authenticated():
        return redirect('main:login')

    # Handle file upload
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = Document(docfile=request.FILES['docfile'])
            newdoc.save()

            # Redirect to the document list after POST
            return redirect('main:upload')
    else:
        form = DocumentForm()  # A empty, unbound form

    # Load documents for the list page
    documents = Document.objects.all()

    # Render list page with the documents and the form
    return render(
        request,
        'pages/upload.html',
        {'documents': documents, 'form': form}
    )


# connect scrapyd service
scrapyd = ScrapydAPI('http://localhost:6800')


def is_valid_url(url):
    validate = URLValidator()
    try:
        validate(url)  # check if url format is valid
    except ValidationError:
        return False

    return True


@csrf_exempt
@require_http_methods(['POST', 'GET'])  # only get and post
def crawl(request):
    # Post requests are for new crawling tasks
    if request.method == 'POST':

        # url = request.POST.get('http://localhost:8000/api/crawl/')
        #
        # if not url:
        #     return JsonResponse({'error': 'Missing  args'})
        #
        # if not is_valid_url(url):
        #     return JsonResponse({'error': 'URL is invalid'})

        url = 'http://localhost:8000/api/crawl'

        domain = urlparse(url).netloc  # parse the url and extract the domain
        unique_id = str(uuid4())  # create a unique ID.

        # This is the custom settings for scrapy spider.

        settings = {
            'unique_id': unique_id,  # unique ID for each record for DB
            'USER_AGENT': 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'
        }

        task = scrapyd.schedule('default', 'scrapingdata', settings=settings, url=url, domain=domain)

        return JsonResponse({'task_id': task, 'unique_id': unique_id, 'status': 'started'})

    # Get requests are for getting result of a specific crawling task
    elif request.method == 'GET':

        task_id = request.GET.get('task_id', None)
        unique_id = request.GET.get('unique_id', None)

        if not task_id or not unique_id:
            return JsonResponse({'error': 'Missing args'})

        status = scrapyd.job_status('default', task_id)
        if status == 'finished':
            try:
                # this is the unique_id that we created even before crawling started.
                item = ScrapyItem.objects.get(unique_id=unique_id)
                return JsonResponse({'data': item.to_dict['data']})
            except Exception as e:
                return JsonResponse({'error': str(e)})
        else:
            return JsonResponse({'status': status})

main/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>{% block title %}{% endblock %} - OWL Unit Tracker </title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

	<!--     Fonts and icons     -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

	<!-- CSS Files -->
    <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{%static 'css/bootstrap-select.css' %}" rel="stylesheet" />
    <link href="{%static 'css/material-kit.css' %}" rel="stylesheet" />

    <link href="{%static 'css/demo.css' %}" rel="stylesheet" />

    {% block additional_styles %}{% endblock %}
</head>

<body class="index-page">
<!-- Navbar -->
<nav class="navbar navbar-fixed-top navbar-openalpr navbar-info">
	<div class="container">
        <div class="navbar-header">
	    	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-index">
	        	<span class="sr-only">Toggle navigation</span>
	        	<span class="icon-bar"></span>
	        	<span class="icon-bar"></span>
	        	<span class="icon-bar"></span>
	    	</button>
	    	<a href="" class="effect-shine">
	        	<div class="logo-container">
                    <div class="logo">
	                    <img src="{% static 'img/new-logo.jpg' %}" style="width: 160px;" alt="openALPR License Generator Logo" rel="tooltip" title="<b>openALPR License Generator</b>" data-placement="bottom" data-html="true">
	                </div>
	                <div class="brand">
	                    OWL Unit Tracker
	                </div>
				</div>
	      	</a>
	    </div>

	    <div class="collapse navbar-collapse" id="navigation-index">
	    	<ul class="nav navbar-nav navbar-right">
				<li>
                    {% if request.user.is_authenticated %}
                        <a rel="tooltip" title="Logout" data-placement="bottom" href="{% url 'main:logout' %}" class="btn btn-white btn-simple btn-just-icon">
                            <i class="fa fa-user-circle"></i>
                        </a>
                    {% else %}
                        <a rel="tooltip" title="Login" data-placement="bottom" href="{% url 'main:login' %}" class="btn btn-white btn-simple btn-just-icon">
                            <i class="fa fa-user-circle"></i>
                        </a>
                    {% endif %}
				</li>
	    	</ul>
	    </div>
	</div>
</nav>
<!-- End Navbar -->

<div class="wrapper">

	<div class="main main-raised" style="margin-top: 0px; padding-top: 70px;">
		{% block content %}{% endblock %}
	</div>

    <footer class="footer">
	    <div class="container">
	        <nav class="pull-left">
	            <ul>

	            </ul>
	        </nav>
	        <div class="copyright pull-right">
	            Copyright &copy; by Container UI 2018. All right reserved.
	        </div>
	    </div>
	</footer>
</div>

</body>

	<!--   Core JS Files   -->
	<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/material.min.js' %}" type="text/javascript"></script>

	<!-- Control Center for Material Kit: activating the ripples, parallax effects, scripts from the example pages etc -->
	<script src="{% static 'js/material-kit.js' %}" type="text/javascript"></script>

    {% block additional_scripts %}{% endblock %}

</html>

main/templates/pages/upload.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block title %}Upload{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}

    <div class="section" style=" background-image: url({% static 'img/background.png' %}); background-position: top center; min-height: 700px;">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="card card-signup">
                        <form class="form upload-form" role="form" method="post" action="{% url "main:upload" %}" enctype="multipart/form-data">

                            {% csrf_token %}

                            <div class="header header-info text-center">
                                <h4>UPLOAD</h4>
                                <div class="social-line">
                                    <a href="https://www.facebook.com/openalpr" class="btn btn-simple btn-just-icon">
                                        <i class="fa fa-facebook-square"></i>
                                    </a>
                                    <a href="https://twitter.com/openalpr" class="btn btn-simple btn-just-icon">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                    <a href="https://www.linkedin.com/company/10472650/" class="btn btn-simple btn-just-icon">
                                        <i class="fa fa-linkedin"></i>
                                    </a>
                                </div>
                            </div>

                            <p class="text-divider">Please upload CSV.</p>

                            {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <p class="text-divider">
                                        </p>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <p class="text-divider">
                                        <div class="alert alert-danger">
                                            <div class="container-fluid">
                                                <div class="alert-icon">
                                                    <i class="material-icons">error_outline</i>
                                                </div>
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true"><i class="material-icons">clear</i></span>
                                                </button>
                                                <b>Error:</b> {{ error|escape }}
                                            </div>
                                        </div>
                                    </p>
                                {% endfor %}
                            {% endif %}

                            <div class="content">

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="input-group">
                                            <span class="input-group-addon">
                                                <i class="material-icons">file_upload</i>
                                                <p>{{ form.non_field_errors }}</p>
                                                <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
                                            </span>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="input-group">
                                            <span class="input-group-addon">
                                                <p>
                                                    {{ form.docfile.errors }}
                                                    {{ form.docfile }}
                                                </p>
                                            </span>
                                        </div>
                                    </div>
                                </div>

                                {% render_field form.next_ %}

                            </div>


                            <div class="footer text-center">
                                <button type="submit" name="upload" id="upload-submit" tabindex="4" class="btn btn-primary" value="Upload" style="margin-top: 50px; margin-bottom: 25px;">Upload InputFile</button>
{#                                <a href="{% url 'main:crawl' %}">#}
{#                                    <button type="button" url="crawl", id="start-button" tabindex="4" class="btn btn-primary" value="StartCrawl" style="margin-top: 50px; margin-bottom: 25px;">Start Crawl</button>#}
{#                                </a>#}
                            </div>

                        </form>
                        <form class="form crawl-form" role="form" method="post" action="{% url "main:crawl" %}">
                            {% csrf_token %}
                            <div class="footer text-center">
                                <button type="submit" id="start-button" class="btn btn-primary" value="crawl" style="margin-top: 50px; margin-bottom: 25px;">Start Crawl</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block additional_scripts %}

{% endblock %}